apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwitter-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwitter-back
  template:
    metadata:
      labels:
        app: pwitter-back
    spec:
      containers:
      - name: pwitter-back
        image: redis
        resources:
          requests:
            cpu: 30m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 128Mi
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: pwitter-back
spec:
  ports:
  - port: 6379
  selector:
    app: pwitter-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwitter-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pwitter-front
  template:
    metadata:
      labels:
        app: pwitter-front
    spec:
      containers:
      - name: pwitter-front
        image: keni7385/pwitter
        resources:
          requests:
            cpu: 30m
            memory: 64Mi
          limits:
            cpu: 2
            memory: 128Mi
        ports:
        - containerPort: 5000
        env:
        - name: DB_ADDRESS
          value: "pwitter-back"
---
apiVersion: v1
kind: Service
metadata:
  name: pwitter-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: pwitter-front