kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  log-format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent rt=$request_time urt=\"$upstream_response_time\" \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
  access-log-off: "false"
  server_names_hash_bucket_size: "128"
