apiVersion: poc.autoscaling.k8s.io/v1alpha1
kind: VerticalPodAutoscaler
metadata:
  name: azure-vote-front-vpa
spec:
  selector:
    matchLabels:
      app: azure-vote-front
  updatePolicy:
    updateMode: "Auto"
