apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: nginx-ingress
spec:
  serviceMonitorSelector:
    matchLabels:
      app: nginx-ingress
  resources:
    requests:
      memory: 400Mi
  scrapeInterval: 10s
