apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress
  labels:
    app: nginx-ingress
spec:
  selector:
    matchLabels:
      app: nginx-ingress
  namespaceSelector:
    matchNames:
    - nginx-ingress
  endpoints: 
  - port: prometheus
  - port: exporter
