apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: custom-metrics
data:
  config.yaml: |
    rules:
    - seriesQuery: 'nginx_exp_http_response_time_seconds_hist_bucket'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        matches: "^(.*)$"
        as: "response_time"
      metricsQuery: 'histogram_quantile(0.9, rate(<<.Series>>{namespace!="",pod!="",status="201",method="POST"}[20s]))'
    - seriesQuery: 'nginx_exp_http_response_count_total'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        matches: "^(.*)$"
        as: "response_count"
      metricsQuery: '<<.Series>>{namespace!="",pod!="",status="201",method="POST"}'